### ISSUE TITLE
Lentezza generale driver

### ISSUE THREAD

**Issue by fdila** [iralabdisco/Azure_Kinect_ROS_Driver#1]
Come riportato anche da un [issue sul repo ufficiale Microsoft](https://github.com/microsoft/Azure_Kinect_ROS_Driver/issues/56), la pubblicazione della point cloud, nel caso in cui si voglia avere anche l'informazione RGB per ogni punto (settando a True il parametro `rgb_point_cloud`), è piuttosto lenta.

Diventa estremamente lenta se il parametro `point_cloud_in_depth_frame` è settato a False, come si vede da ros2 topic hz:

```
average rate: 0.385
	min: 0.142s max: 13.986s std dev: 3.44101s window: 16
```

Se invece il parametro point_cloud_in_depth_frame` è settato a True si hanno dei risultati un po' più accettabili, anche se in teoria è impostato per andare a 30 FPS:

```
average rate: 15.091
	min: 0.018s max: 0.764s std dev: 0.08649s window: 802
```

**Comment by fdila** [comment]
@chferra
Stiamo continuando a notate n-mila problemi di lentezza con il driver, sia sul NUC che sul mio portatile (che per reference è un HP ProBook 450 15.6 inch G10).

Possibili varie ed eventuali problematiche:

- SDK che teoricamente non è compatibile con ubuntu 22.04? 
- Qualche tipo di incompatibilità hw con mio pc/nuc?
- Problemi con qualcosa di "basso livello" relativi a linux?
- Problemi relativi al nodo ROS?

A proposito del primo/secondo punto, cercando di escludere qualche possibile causa, ho registrato con k4recorder un .mkv usando l'sdk su windows, lo metto qui: https://drive.google.com/drive/folders/1v38kMCr07yvsNEQk7HlB7SNpZC3l8qzY?usp=drive_link

**Comment by fdila** [comment]
Per iniziare a escludere i problemi legati a hw, sdk e s.o. ho registrato anche un mkv con k4arecorder da linux (sempre su mio portatile, e sempre caricato nella cartella linkata).

Andando ad analizzare entrambi gli mkv, estraendo i frame depth con ffmpeg come specificato da mamma microsoft (https://learn.microsoft.com/en-us/azure/kinect-dk/record-file-format) il numero di frame torna, gli mkv sono registrati a 30FPS e estraendo tutti i frame depth viene un numero che è uguale a durata_video*30

Provando però a usare il nodo ros kinect e dandogli come input i suddetti mkv il rate delle immagini di depth è randomicamente più basso.

**Comment by chferra** [comment]
@fdila 
Provando sul fisso (hw di 10 anni fa, CPU intel 1150 i5-4690K) non sembrerebbero esserci problemi. Il topic /points2 pubblica a praticamente 30hz in maniera costante, sia con l'opzione rgb attivata che non:
![Screenshot from 2024-06-04 18-31-51](https://github.com/iralabdisco/Azure_Kinect_ROS_Driver/assets/24875783/8ed4e4d7-2ad2-4c63-8c68-b0c58c5b9437)
![Screenshot from 2024-06-04 18-32-26](https://github.com/iralabdisco/Azure_Kinect_ROS_Driver/assets/24875783/e3242a75-af61-4123-9a33-70ec617e551a)

Inoltre, provando a usare il nodo ros per il kinect, dando in input gli mkv che hai condiviso, non mi risulta il fatto che il rate delle immagini depth sia più basso:
![Screenshot from 2024-06-04 19-04-58](https://github.com/iralabdisco/Azure_Kinect_ROS_Driver/assets/24875783/9e2061dc-eb77-463f-9d74-6b1ef02928b3)
![Screenshot from 2024-06-04 19-05-30](https://github.com/iralabdisco/Azure_Kinect_ROS_Driver/assets/24875783/1473a753-c99b-488b-bdd7-ff87f06a229b)
E stesso discorso per le pointcloud:
![Screenshot from 2024-06-04 19-07-25](https://github.com/iralabdisco/Azure_Kinect_ROS_Driver/assets/24875783/4342470f-e6e1-4be0-84cb-6de14cfccb59)

Quindi a questo punto, dato che sul mio portatile lenovo C740 (morto purtroppo) e fisso non parrebbe esserci questo problema, forse potrebbe invece essere plausibile attribuire il problema a incompatibiltà con hw "abbastanza" nuovi.

**Comment by fdila** [comment]
Sto provando sul mio vecchio thinkpad (t480 con i5) usando gli mkv e funziona (circa, in realtà se abilito la pubblicazione della point cloud colorata va a ~15hz, lasciando invece la point cloud senza colore va a 30hz come dovrebbe).
Sto provando a lasciare in loop l'mkv (mettendo il parametro recording_loop_enabled a true) e lasciandolo andare per un po' di tempo il rate di pubblicazione inizia a scendere lentamente, dopo una mezz'oretta siamo a 26hz al posto di 30.
Così per sport provo a lasciarlo andare tutta notte e vedo che succede, ma direi che c'è un qualche problema nel nodo ROS, (memory leak? devo davvero imparare il c++ prima o poi), e questo problema per qualche motivo si sente molto di più sulle cpu nuove?
@chferra se non hai di meglio da fare lascialo andare anche tu per qualche ora in loop, sono curiosa.

**Comment by chferra** [comment]
per adesso, dopo 40 minuti, non riscontro differenze

**Comment by chferra** [comment]
anche dopo una notte in loop, a me rimane fisso a 30 (modalità rgb attiva)

**Comment by chferra** [comment]
@fdila
mi dicevi che il codice cinese, che dovrebbe dare continuità al supporto, non funziona. Ti riferivi all'SDK? Quasi quasi proverei a vedere se funziona sul mio pc.
Se il problema é davvero hw non so quanto si possa fare se non sperare nel supporto dell'azienda cinese... capire il problema nel loro codice e intervenire mi sembra piuttosto challenging

**Comment by fdila** [comment]
Rispondo in ordine:

- in effetti lasciandolo la notte anche a me è tornato a 30, sarà che mentre facevo andare ieri sera avevo anche chrome aperto e stavo facendo altro
- lascierei stare il robo cinese, visto che anche loro dicono che il kinect non è supportato, era più un tentativo dato dalla disperazione ieri
- continuo a non spiegarmi che problemi stia avendo il nodo ros. se fosse qualcosa di interazione hw pc-kinect il problema si dovrebbe presentare anche usando k4arecorder, che invece registra tranquillamente a 30fps. ho registrato un mkv anche dal nuc e anche lì va tranquillo a 30fps

**Comment by chferra** [comment]
(3) sì in effetti ha senso.
Sul tuo pc (quello nuovo) non vedi warning o errori particolari sul nodo ros, vero?

**Comment by fdila** [comment]
Habemus (circa) risposta: è ROS 2 ad essere rotto, in particolare il tool `ros2 hz`.

Per motivi mistici, che non ho approfondito al momento ma che mi piacerebbe capire, `ros2 hz` con messaggi "grossi" (inteso come numero di byte per messaggio) si rompe, in realtà il driver è sempre andato a 30hz ed era solo il tool di monitoring a riportare i dati sbagliati.
Per avere conferma della cosa ho scritto un nodo stupidissimo che si sottoscrive ai topic di depth, rgb e pointcloud e pubblica su altrettanti topic un messaggio di tipo String con il conteggio dei messaggi ricevuti.
Tipo si sottoscrive a `/depth/image_raw` e ogni volta che ascolta un messaggio su quel topic pubblica su `/ak_debug/depth_image_raw_received` un messaggio String con il numero di immagini depth ricevute fino a quel momento.
Monitorando poi questo ultimo topic la frequenza è quella che ci aspettiamo :)

![Screenshot from 2024-06-05 16-43-50](https://github.com/iralabdisco/Azure_Kinect_ROS_Driver/assets/32036043/f6f78173-9cb7-4efd-9885-977ef4c46ac4)
 
 Per i posteri, il nodo che ho scritto l'ho messo qui: https://github.com/iralabdisco/azure_kinect_debugger

**Comment by fdila** [comment]
Per reference non siamo i soli ad aver avuto questo problema: https://answers.ros.org/question/350753/ros2-topic-hz-provides-wrong-rate-for-larger-msgs/

Vorrei anche capire perchè sul mio pc vecchio/quello di Christian questo problema non si verifica, ma per ora mi accontento di avere una risposta sul driver.

**Comment by fdila** [comment]
(ho provato a buttar via del tempo per capire perchè sul mio pc nuovo `ros2 topic hz` non funzioni e sul vecchio thinkpad invece sì, ma non ne sono venuta a capo. in ogni caso direi che per il futuro non ci affideremo a questo tool e amen, chiudo l'issue)
